# Generated by Django 4.1.1 on 2022-09-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="comment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="comments.comment",
            ),
        ),
    ]
