# Generated by Django 4.1 on 2022-09-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="description",
        ),
    ]
