# Generated by Django 4.1 on 2022-09-09 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_remove_comment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=130),
            preserve_default=False,
        ),
    ]
