# Generated by Django 4.1 on 2022-09-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_user"),
        ("comments", "0005_comment_description"),
    ]

    operations = []
