# Generated by Django 4.1.1 on 2022-09-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="update_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
